{{
    config(
        materialized='incremental',
		unique_key='upload_id'
    )
}}

with warehouse_log as ( select * from {{ source('clture_production_db', 'warehouse_log') }} )

select *
	,case when service = 'GOOGLE' then 
		case 
			when destination_path ilike '%Money%sends%' then 'money_sends_and_requests'
			when destination_path ilike '%metadata.csv%' then 'metadata'
			when destination_path ilike '%Favorite%places%' then 'favorite_places'
			when destination_path ilike '%Favorite%image%' then 'favorite_images'
			when destination_path ilike '%Favorite%pages%' then 'favorite_pages'
			when destination_path ilike '%Favorite%jobs%' then 'favorite_jobs'
			when destination_path ilike '%want%to%go%' then 'want_to_go'
			when destination_path ilike '%memes%' then 'memes'
			when destination_path ilike '%Default%lis%' then 'memes'
			when destination_path ilike '%Printers%Metadata%Takeout%' then 'printer_metadata'
			when destination_path ilike '%Jobs%Metadata%Takeout%' then 'jobs_metadata'
			when destination_path ilike '%music-uploads-metadata%' then 'music_upload_metadata'
			when destination_path ilike '%notification_tokens%' then 'notification_tokens'
			when destination_path ilike '%mobile_devices%' then 'mobile_devices'
			when destination_path ilike '%device_history%' then 'device_history'
			when destination_path ilike '%account%' then 'account'
			when destination_path ilike '%whispersync%' then 'whisper_sync'
			when destination_path ilike '%My%shopping%list%' then 'shopping_list'
			when destination_path ilike '%reading_list%' then 'reading_list'
			when destination_path ilike '%OrderHistory%' then 'order_history'
			when destination_path ilike '%transactions%' then 'transactions'
			when destination_path ilike '%members%' then 'members'
			when destination_path ilike '%sensors%' then 'sensors'
			when destination_path ilike '%Dictionary%' then 'dictionary'
			when destination_path ilike '%Money%remittances%requests%' then 'money_remittance_requests'
			when destination_path ilike '%Daily%Summaries%' then 'daily_summaries'
			when destination_path ilike '%Retail.OrdersReturned.Payments%' then 'retail_orders_returned_payments'
			when destination_path ilike '%Envois%et%demandes%d_argent%'  then 'money_orders_and_requests'
			when destination_path ilike '%Retail.CustomerReturns%' then 'retail_customer_returns'
			when destination_path ilike '%followers%' then 'followers'
			when destination_path ilike '%settings%' then 'settings'
			when destination_path ilike '%profile%' then 'profile'
			when destination_path ilike '%Your%personalization%feedback%' then 'personalized_feedback'
			when destination_path ilike '%recently_viewed_groups%' then 'recently_viewed_groups'
			when destination_path ilike '%recently_viewed_discussions%' then 'recently_viewed_discussions'
			when destination_path ilike '%pappusagedatasetting%' then 'app_usage_data_setting'
			when destination_path ilike '%watch-history%' then 'watch_history'
			when destination_path ilike '%search-history%' then 'search_history'
			when destination_path ilike '%MyActivity%' then 'my_activity'
			when destination_path ilike '%all-playlists%' then 'all_playlist'
			when destination_path ilike '%21 Days to Freedom%' then '21_days_to_freedom'
			when destination_path ilike '%Blocked Addresses%' then 'blocked_addresses'
			when destination_path ilike '%BrowserHistory%' then 'browser_history'
			when destination_path ilike '%businessPersonalization%' then 'businessPersonalization'
			when destination_path ilike '%Data Recovery%' then 'data_recovery'
			when destination_path ilike '%Delegated Sender Addresses%' then 'delegated_sender_addresses'
			when destination_path ilike '%Facebook video%' then 'facebook_video'
			when destination_path ilike '%Favorite workouts%' then 'favorite_workouts'
			when destination_path ilike '%Fitness Training%' then 'fitness_training'
			when destination_path ilike '%Forwarding Addresses%' then 'forwarding_addresses'
			when destination_path ilike '%Health and wellness%' then 'health_and_wellness'
			when destination_path ilike '%Healthy Foods List%' then 'healthy_foods_list'
			when destination_path ilike '%HomeApp%' then 'home_app'
			when destination_path ilike '%HomeHistory%' then 'home_history'
			when destination_path ilike '%Immediate Needs%' then 'immediate_needs'
			when destination_path ilike '%Liked videos%' then 'liked_videos'
			when destination_path ilike '%Linked Services%' then 'linked_services'
			when destination_path ilike '%Location History%' then 'location_history'
			when destination_path ilike '%music-library-songs%' then 'music_library_songs'
			when destination_path ilike '%Music New%' then 'music_new'
			when destination_path ilike '%My Activity History%' then 'my_activity'
			when destination_path ilike '%Nature Sounds%' then 'nature_sounds'
			when destination_path ilike '%Notification Preferences%' then 'notification_preferences'
			when destination_path ilike '%Order History%' then 'order_history'
			when destination_path ilike '%Other Mail%' then 'other_mail'
			when destination_path ilike '%Podcast%' then 'podcast'
			when destination_path ilike '%Post Malone%' then 'post_malone'
			when destination_path ilike '%Purchases%' then 'purchase'
			when destination_path ilike '%Purchase History%' then 'purchase_history'
			when destination_path ilike '%Questions and Answers%' then 'questions_and_answers'
			when destination_path ilike '%Real estate%' then 'real_estate'
			when destination_path ilike '%Redemption History%' then 'redemption_history'
			when destination_path ilike '%Redemption Song%' then 'redemption_song'
			when destination_path ilike '%Screenshot%Camera%' then 'screenshot_camera'
			when destination_path ilike '%Screenshot%Chrome%' then 'screenshot_chrome'
			when destination_path ilike '%Screenshot%Drive%' then 'screenshot_drive'
			when destination_path ilike '%Screenshot%Facebook%' then 'screenshot_facebook'
			when destination_path ilike '%Screenshot%Gallery%' then 'screenshot_gallery'
			when destination_path ilike '%Screenshot%Gmail%' then 'screenshot_gmail'
			when destination_path ilike '%Screenshot%Instagram%' then 'screenshot_instagram'
			when destination_path ilike '%Screenshot%Messages%' then 'screenshot_messages'
			when destination_path ilike '%Screenshot%Messenger%' then 'screenshot_messenger'
			when destination_path ilike '%Screenshot%Nordstrom%' then 'screenshot_nordstrom'
			when destination_path ilike '%Screenshot%One UI Home%' then 'screenshot_one_ui_home'
			when destination_path ilike '%Screenshot%OneDrive%' then 'screenshot_onedrive'
			when destination_path ilike '%Screenshot%Samsung Internet%' then 'screenshot_samsung_internet'
			when destination_path ilike '%Screenshot%Tasker%' then 'screenshot_tasker'
			when destination_path ilike '%Screenshot%Twitter%' then 'screenshot_twitter'
			when destination_path ilike '%Screenshot%WhatAapp%' then 'screenshot_whatsapp'
			when destination_path ilike '%Screenshot%Yahoo Mail%' then 'screenshot_yahoo_mail'
			when destination_path ilike '%SearchEngines%' then 'searchengines'
			when destination_path ilike '%Seed Health%' then 'seed_health'
			when destination_path ilike '%Series-metadata%' then 'series_metadata'
			when destination_path ilike '%shared_album_comments%' then 'shared_album_comments'
			when destination_path ilike '%Shopping list%' then 'shopping_list'
			when destination_path ilike '%Shopping%' then 'shopping'
			when destination_path ilike '%SoundSensing%' then 'soundsensing'
			when destination_path ilike '%Speechless%' then 'speechless'
			when destination_path ilike '%SportsConnect%metadata%' then 'sports_connect_metadata'
			when destination_path ilike '%Streaming Services%' then 'streaming_services'
			when destination_path ilike '%Subnetting%' then 'Subnetting'
			when destination_path ilike '%Subscriptions%' then 'subscription'
			when destination_path ilike '%Suffocate%' then 'suffocate'
			when destination_path ilike '%Sunday In The Shower%' then 'sunday_in_the_shower'
			when destination_path ilike '%Sweet November%' then 'sweet_november'
			when destination_path ilike '%tempImageForSave%' then 'temp_image_for_save'
			when destination_path ilike '%toutes-playlists%' then 'toutes_playlists'
			when destination_path ilike '%Video Editing%' then 'video_editing'
			when destination_path ilike '%Video Reel%' then 'video_reel'
			when destination_path ilike '%wallpaper%' then 'wallpaper'
			when destination_path ilike '%watch-later%' then 'watch_later'
			when destination_path ilike '%WEEKLY TO DO_S%' then 'weekly_to_do_s'
			when destination_path ilike '%Workout%' then 'workout'
			when destination_path ilike '%Worship%' then 'worship'
			when destination_path ilike '%Ads%metadata%' then 'ads_metadata'
			when destination_path ilike '%ambience%' then 'ambience'
			when destination_path ilike '%ANIMATION%' then 'animation'
			when destination_path ilike '%Audiobook%' then 'audiobook'
			when destination_path ilike '%Autofill%' then 'autofill'
			when destination_path ilike '%Birthday%metadata%' then 'birthday_metadata'
			when destination_path ilike '%Burn%' then 'burn'
			when destination_path ilike '%Blogged%' then 'blogged'
			when destination_path ilike '%Contagious%' then 'contagious'
			when destination_path ilike '%COLLAGE%' then 'collage'
			when destination_path ilike '%Devices%' then 'devices'
			when destination_path ilike '%Documentary%' then 'documentary'
			when destination_path ilike '%e-mail list%' then 'e-mail_list'
			when destination_path ilike '%Emotional%' then 'emotion'
			when destination_path ilike '%Exercise%' then 'exercise'
			when destination_path ilike '%Extensions%' then 'extensions'
			when destination_path ilike '%Favorites%' then 'favorites'
			when destination_path ilike '%Fitness%' then 'fitness'
			when destination_path ilike '%HAIR%' then 'hair'
			when destination_path ilike '%Hangouts%' then 'hangouts'
			when destination_path ilike '%Health%' and destination_path not ilike '%wellness%' and destination_path not ilike '%Seed%' and destination_path not ilike '%Healthy%' then 'health'
			when destination_path ilike '%Installs%' then 'installs'
			when destination_path ilike '%Instrumentals%' then 'instrumentals'
			when destination_path ilike '%likes%' then 'likes'
			when destination_path ilike '%Love%' then 'love'
			when destination_path ilike '%Makeup%' then 'makeup'
			when destination_path ilike '%Meditations%' then 'meditation'
			when destination_path ilike '%MOTION%' then 'motion'
			when destination_path ilike '%Questions%' and  destination_path not ilike '%Answers%' then 'questions'
			when destination_path ilike '%Random%' then 'random'
			when destination_path ilike '%Ratings%' then 'ratings'
			when destination_path ilike '%received%.jpeg%' then 'received_jpeg'
			when destination_path ilike '%Recipes%' then 'recipes'
			when destination_path ilike '%Resized%' then 'resized'
			when destination_path ilike '%Restart%' then 'restart'
			when destination_path ilike '%Reviews%' then 'reviews'
			when destination_path ilike '%save-new%' then 'save-new'
			when destination_path ilike '%Signatures%' then 'signatures'
			when destination_path ilike '%Snapchat%.jpg%' then 'snapchat_jpg'
			when destination_path ilike '%Track%' then 'track'
			when destination_path ilike '%Under%' then 'under'
			when destination_path ilike '%Uploads%' then 'uploads'
			when destination_path ilike '%Vegan%' then 'vegan'
			when destination_path ilike '%_VID_%.mp4%' then 'vid_mp4'
			when destination_path ilike '%SEPTEMBER%' then 'september'
			when destination_path ilike '%OCTOBER%' then 'october'
			when destination_path ilike '%NOVEMBER%' then 'november'
			when destination_path ilike '%MAY%' then 'may'
			when destination_path ilike '%MARCH%' then 'march'
			when destination_path ilike '%metadata%' then 'metadata'
			when destination_path ilike '%JULY%' then 'july'
			when destination_path ilike '%JUNE%' then 'june'
			when destination_path ilike '%Library%' then 'library'
			when destination_path ilike '%JANUARY%' then 'january'
			when destination_path ilike '%APRIL%' then 'april'
			when destination_path ilike '%AUGUST%' then 'august'
			when destination_path ilike '%DECEMBER%' then 'december'
			when destination_path ilike '%FEBRUARY%' then 'february'
			when destination_path ilike '%_data%' then 'data'
			when destination_path ilike '%google% _food%' then 'google_food'
			when destination_path ilike '%google_play-movies%' then 'google_play_movies'
			when destination_path ilike '%google%.jpg%' then 'google_jpg_other'
			when destination_path ilike '%google%.mp3%' then 'google_mp3_other'
			when destination_path ilike '%google%.mp4%' then 'google_mp4_other'
			when destination_path ilike '%google_youtube%.jpg%' then 'google_youtube_jpg_other'
			when destination_path ilike '%google%.csv%' then 'google_csv_other'
			when destination_path ilike '%google%.json%' then 'google_json_other'
				else 'google_other'
			end
		when service = 'AMAZON' then 
		case 
			when destination_path ilike '%account%info%' then 'account_info'
			when destination_path ilike '%Accounts.csv' and destination_path not ilike '%twitch%' then 'account'
			when destination_path ilike '%Advertising.3PAudiences%' then 'advertising_3p_audiences'
			when destination_path ilike '%Advertising.AdvertiserAudiences%' then 'advertising_advertising_audiences'
			when destination_path ilike '%Advertising.AdvertiserClicks%' then 'advertising_advertiser_clicks'
			when destination_path ilike '%Advertising.AmazonAudience%' then 'advertising_amazon_audiences'
			when destination_path ilike '%Advertising.OptOut%' then 'advertising_opt_out'
			when destination_path ilike '%Alexa%Echo%Devices.Hint%Responses.ShoppingAnalytics%' then 'alexa_echo_hint_responses_shopping_analytics'
			when destination_path ilike '%Alexa%Echo%Devices.Notification%Opt-ins.ShoppingAnalytics%' then 'alexa_echo_notification_opt_in_shopping_analytics'
			when destination_path ilike '%Alexa%Echo%Devices.Notification%Preferences.ShoppingAnalytics%' then 'alexa_echo_notification_preferences_shopping_analytics'
			when destination_path ilike '%Alexa%Echo%Devices.Shopping%Lists.ShoppingAnalytics%' then 'alexa_echo_shopping_lists_shopping_analytics'
			when destination_path ilike '%AlexaPolicyInstructions%' then 'alexa_policy_instructions'
			when destination_path ilike '%Amazon%Prime%Location%Data%' then 'prime_location'
			when destination_path ilike '%Amazon%Prime%WatchList%' then 'prime_watchlist'
			when destination_path ilike '%Amazon.Forms%' then 'amazon_forms'
			when (destination_path ilike '%amazon_digital-content-ownership%' and destination_path not ilike '%viewing%') then 'amazon_digital_content_ownership'
			when destination_path ilike '%Alarms%' and destination_path not ilike '%music%' then 'alarms'
			when destination_path ilike '%AmazonGames.TwitchPrime.AccountHistory%' then 'twitch_prime_account_history'
			when destination_path ilike '%AmazonGames.TwitchPrime.ClaimedOffers%' then 'twitch_prime_claimed_offers'
			when destination_path ilike '%AmazonGames.TwitchPrime.LinkedTwitch%' then 'twitch_prime_linked_twitch_accounts'
			when destination_path ilike '%AmazonGames.TwitchPrime.SubscriptionCreditHistory%' then 'twitch_prime_subscription_credit_history'
			when destination_path ilike '%AmazonPayBrowserBehaviorData%' then 'pay_browser_behavior'
			when destination_path ilike '%AmazonPayOrderDetails%' then 'pay_order_details'
			when destination_path ilike '%AmazonSmile.AggregateCustomerDonation.Data%' then 'smile_aggregate_customer_donation'
			when destination_path ilike '%AmazonSmile.CharitySelectionHistory.Data%' then 'smile_charity_selection_history'
			when destination_path ilike '%AmazonSmile.CustomerEngagementCampaignCurrentStatus%' then 'smile_customer_engagement_campaign_current_status'
			when destination_path ilike '%AmazonSmile.CustomerEngagementCampaignHistory%' then 'smile_customer_engagement_campaign_history'
			when destination_path ilike '%AmazonSmile.CustomerEngagementCampaignHistory.Description%' then 'smile_customer_engagement_campaign_history_description'
			when destination_path ilike '%AmazonSmile.CustomerMobileAppStatusHistory.Data%' then 'smile_customer_mobile_app_status_history'
			when destination_path ilike '%Answers Notifications%' then 'answers_notifcations'
			when destination_path ilike '%AnswerNotificationRequests%' then 'answer_notification_requests'
			when destination_path ilike '%appengagement%' then 'app_engagement'
			when destination_path ilike '%Apps.AmazonAssistant.FeedItemInteractions%' then 'amazon_assistant_feed_item_interactions'
			when destination_path ilike '%AppsAndMore.AmazonAssistantAppAndExtension.EngagementViewData1%' then 'amazon_assistant_engagement_view'
			when destination_path ilike '%AppsAndMore.AmazonAssistantAppAndExtension.XCompEngagementViewData1%' then 'amazon_assistant_xcomp_engagement_view'
			when destination_path ilike '%AppsAndMore.AmazonAssistantAppAndExtension.XCompWorkflowViewData1%' then 'amazon_assistant_xcomp_workflow_view'
			when destination_path ilike '%appstore-clickstream-tablet-insider-engagement%' then 'app_store_click_stream_tablet_insider_enagagement'
			when destination_path ilike '%appstore-firetv-app-details-page%' 
				and not (destination_path ilike '%carousel%' 
					or destination_path ilike '%item%' 
					or destination_path ilike '%dialogs%' 
				 ) then 'app_store_fire_tv_app_details_page'
			when destination_path ilike '%appstore-firetv-app-details-page-carousel%' and destination_path not ilike '%item%' then 'app_store_fire_tv_app_details_page_carousel'
			when destination_path ilike '%appstore-firetv-app-details-page-carousel-item%' then 'app_store_fire_tv_app_details_page_carousel_item'
			when destination_path ilike '%appstore-firetv-app-details-page-dialogs%' then 'app_store_fire_tv_app_details_page_dialogs'
			when destination_path ilike '%appstore-firetv-buybox%' then 'fire_tv_app_store_buy_box'
			when destination_path ilike '%Appstore-GameCircle.Achievements%' then 'app_store_game_circle_achievements'
			when destination_path ilike '%Appstore-GameCircle.Badge_Progress%' then 'app_store_game_circle_badge_progress'
			when destination_path ilike '%Appstore-GameCircle.Earned_Experience%' then 'app_store_game_circle_earned_experience'
			when destination_path ilike '%Appstore-GameCircle.Game_Scores%' then 'app_store_game_circle_game_scores'
			when destination_path ilike '%Appstore-GameCircle.Game_Time%' then 'app_store_game_circle_game_time'
			when destination_path ilike '%Appstore-GameCircle.Profile_Information%' then  'app_store_game_circle_profile_information'
			when destination_path ilike '%Appstore-GameCircle.Registered_Devices%' then 'app_store_game_circle_registered_devices'
			when destination_path ilike '%Appstore-GameCircle.ShowCased%' then 'app_store_game_circle_show_cased'
			when destination_path ilike '%Appstore-GameCircle.Total_Experience%' then 'app_store_game_circle_total_experience'
			when destination_path ilike '%Appstore.InAppPurchases.ClaimJumperAudits%' then 'app_store_in_app_purchases_claim_jumper_audits'
			when destination_path ilike '%Appstore.InAppPurchases.SubscriptionReceipts-US%' then 'app_store_in_app_purchases_subscription_receipts'
			when destination_path ilike '%appusagedatasetting%' then 'app_usage_data_setting'
			when destination_path ilike '%Audible.Credits%' then 'audible_credit'
			when destination_path ilike '%Audible.DevicesActivations%' then 'audible_devices_activitations'
			when destination_path ilike '%Audible.Gifts%' then 'audible_gifts'
			when destination_path ilike '%Audible.Library%' then 'audible_library'
			when destination_path ilike '%Audible.Listening%' then 'audible_listening'
			when destination_path ilike '%Audible.MembershipBillings%' then 'audible_membership_billings'
			when destination_path ilike '%Audible.Promotions%' then 'audbile_promotions'
			when destination_path ilike '%Audible.PurchaseHistory%' then 'audible_purchase_history'
			when destination_path ilike '%Audible.SendABook%' then 'audible_send_book'
			when destination_path ilike '%Audible.Wishlist%' then 'audible_wishlish'
			when destination_path ilike '%Audible.WhisperSync%' then 'audible_whisper_sync'
			when destination_path ilike '%AudioGroup%' then 'audio_group'
			when destination_path ilike '%Away Lighting History%' then 'away_lightning_history'
			when destination_path ilike '%Away Lighting Status%' then 'away_lightning_status'
			when destination_path ilike '%BookRelation%' then 'book_relation'
			when destination_path ilike '%Calendars%' then 'calendars'
			when destination_path ilike '%Camera Updates%' then 'camera_updates'
			when destination_path ilike '%client_events%' then 'client_events'
			when destination_path ilike '%CollectorList%' then 'collector_list'
			when destination_path ilike '%Customer Default Provider Preferences%' then 'customer_default_provider_preferences'
			when destination_path ilike '%CustomerCommunicationExperience.Preferences%' then 'customer_communication_experience_preferences'
			when destination_path ilike '%CustomerInterests%' then 'customer_interests'
			when destination_path ilike '%Device Configuration%' then 'device_configuration'
			when destination_path ilike '%Device Configuration History%' then 'device_configuration_history'
			when destination_path ilike '%Device State%' then 'device_state'
			when destination_path ilike '%device_info%' then 'device_info'
			when destination_path ilike '%deviceengagement%' then 'device_engagement'
			when destination_path ilike '%DevicePairings%' then 'device_pairings'
			when destination_path ilike '%Device%Data%' then 'device_data'
			when destination_path ilike '%Devices.Kindle.ReadingActions%' then 'kindle_devices_reading_actions'
			when destination_path ilike '%Devices.Kindle.ReadingSessions%' then 'kindle_devices_reading_sessions'
			when destination_path ilike '%deviceusagedatasetting%' then 'device_usage_data_setting'
			when destination_path ilike '%digital-content-ownership%Amazonlistening%' then 'digital_content_ownership_listening'
			when destination_path ilike '%digital-content-ownership%AmazonMusiclibrary%' then 'digital_content_ownership_music_library'
			when destination_path ilike '%Digital.ActionBenefit%' then 'digital_action_benefit'
			when destination_path ilike '%Digital.Borrows%' then 'digital_borrows'
			when destination_path ilike '%Digital.CustomerAttributes%' then 'digital_customer_attributes'
			when destination_path ilike '%Digital.CustomerAttributes%' then 'digital_customer_attributes'
			when destination_path ilike '%Digital.CustomerAttributes.1.csv%' then 'customer_attributes'
			when destination_path ilike '%Digital.Orders.Returns%' then 'digital_orders_returns'
			when destination_path ilike '%DigitalMusicTrack%' then 'digital_music_track'
			when destination_path ilike '%DigitalMusic%' then 'digital_music'
			when destination_path ilike '%Digital.PrimeVideo.CustomerTitleRelevanceRecommendations%' then 'prime_customer_title_relevance_recommendations'
			when destination_path ilike '%Digital.PrimeVideo.LocationData%' then 'location_data'
			when destination_path ilike '%Digital.PrimeVideo.ViewCounts%' then 'view_counts'
			when destination_path ilike '%Digital.PrimeVideo.Watchlist%' then 'digital_prime_video_watchlist'
			when destination_path ilike '%Digital.Redemption%' then 'digital_redemption'
			when destination_path ilike '%Digital.PrimeVideo.ParentalControlsSettings%' then 'parental_control_settings'
			when destination_path ilike '%Digital.PrimeVideo.PinSettings%' then 'pin_setting'
			when destination_path ilike '%DigitalOrderHistory%' then 'digital_order_history'
			when destination_path ilike '%Dismissed%' then 'dismissed'
			when destination_path ilike '%FamilyCustomerPreference%' then 'family_customer_preference'
			when destination_path ilike '%Feedback%' then 'feedback'
			when destination_path ilike '%FireTv-Glossary%' then 'fire_tv_glossary'
			when destination_path ilike '%Gadgets%' then 'gadgets'
			when destination_path ilike '%Geolocation%' then 'geolocation'
			when destination_path ilike '%GENERAL_SETTINGS%' then 'general_settings'
			when destination_path ilike '%guestlist%' then 'guestlist'
			when destination_path ilike '%Historical%Music%Queue%Items%' then 'historical_music_queue_items'
			when destination_path ilike '%Historical%Music%Queues%' then 'historical_music_queues'
			when destination_path like '%Hunches%' then 'hunches'
			when destination_path ilike '%_IMG%' then 'image'
			when destination_path ilike '%JDunston%' then 'jdunston'
			when destination_path ilike '%KindleEBook%' then 'kindle_ebook'
			when destination_path ilike '%Kindle_Periodicals%' then 'kindle_periodicals'
			when destination_path ilike '%Kindle.Periodicals.ContentExplorer_Events%' then 'kindle_periodicals_content_explorer_events'
			when destination_path ilike '%Kindle.AuthorFollows.AuthorRecommendations%' then 'kindle_author_follow_author_recommendations'
			when destination_path ilike '%Kindle.BooksPromotions.ManuallyCuratedRewardOffers%' then 'kindle_books_promotion_manual_reward_offers'
			when destination_path ilike '%Kindle.BooksPromotions.RewardOfferRepository%' then 'kindle_books_promotion_reward_offer_repository'
			when destination_path ilike '%Kindle.Devices.ApplicationSession%' then 'kindle_devices_kindle_application_session'
			when destination_path ilike '%Kindle.Devices.autoMarkAsRead%' then 'kindle_devices_kindle_auto_mark_read'
			when destination_path ilike '%Kindle.Devices.kindleBookmarkActions%' then 'kindle_devices_kindle_bookmark_actions'
			when destination_path ilike '%Kindle.Devices.kindleHighlightActions%' then 'kindle_devices_kindle_highlight_action'
			when destination_path ilike '%Kindle.Devices.kindleNoteActions%' then 'kindle_devices_kindle_note_actions'
			when destination_path ilike '%Kindle.Devices.kindleNotebookActions%' then 'kindle_devices_kindle_notebook_actions'
			when destination_path ilike '%Kindle.Devices.kindleQuoteShareActions%' then 'kindle_devices_kindle_quote_share_actions'
			when destination_path ilike '%Kindle.Devices.kindleSearchActions%' then 'kindle_devices_kindle_search_actions'
			when destination_path ilike '%Kindle.Devices.kindleXrayActions%' then 'kindle_devices_kindle_xray_actions'
			when destination_path ilike '%Kindle.Devices.ReadingActions%' then 'kindle_devices_reading_actions'
			when destination_path ilike '%Kindle.Devices.ReadingSessions%' then 'kindle_devices_reading_sessions'
			when destination_path ilike '%Kindle.Devices.ReadingSessionVersion2%' then 'kindle_devices_reading_session_version'
			when destination_path ilike '%Kindle.Devices.readerLibrarySeriesGroupingMetrics%' then 'kindle_devices_reader_library_series_grouping_metrics'
			when destination_path ilike '%Kindle.Devices.screensaverInfo%' then 'kindle_devices_screen_saver_info'
			when destination_path ilike '%Kindle.Devices.showBookCoversOnAppResume%' then 'kindle_devices_shows_book_cover_resume'
			when destination_path ilike '%Kindle.KindleBenefits.GreatOnKindleTransaction%' then 'kindle_kindle_benefits_great_on_kindle_transaction'
			when destination_path ilike '%Kindle.KindleDocs.DocumentMetadata%' then 'kindle_kindle_docs_document_metadata'
			when destination_path ilike '%Kindle.KindleDocs.KindleAliasToDeviceMapping%' then 'kindle_kindle_docs_alias_device_mapping'
			when destination_path ilike '%Kindle.KindleHome.CardClicksOnKindleForAndroidV2%' then 'kindle_kindle_home_card_clicks_android'
			when destination_path ilike '%Kindle.KindleHome.CardClicksOnKindleForiOS%' then 'kindle_kindle_home_card_clicks_ios'
			when destination_path ilike '%Kindle.KindleHome.CardViewsOnKindleForAndroidV2%' then 'kindle_kindle_home_card_views_android'
			when destination_path ilike '%Kindle.KindleHome.CardViewsOnKindleForiOS%' then 'kindle_kindle_home_card_views_ios'
			when destination_path ilike '%Kindle.Periodicals.ContentExplorer_Events%' then 'kindle_periodicals_content_explorer_events'
			when destination_path ilike '%KindlePDoc%' then 'kindle_doc'
			when destination_path ilike '%KindleMagazine%' then 'kindle_magazine'
			when destination_path ilike '%Kindle.Reach.KindleHome.CardClicksOnKindleForAndroid%' then 'kindle_reach_kindle_home_card_clicks_on_android'
			when destination_path ilike '%Kindle.Reach.KindleHome.CardViewsOnKindleForAndroid%' then 'kindle_reach_kindle_home_card_views_on_android'
			when destination_path ilike '%Kindle.Reach.KindleNotifications.CustomerNotificationEvents%' then 'kindle_reach_kindle_notifications_customer_notification_events'
			when destination_path ilike '%Kindle.Reach.KindleNotifications.DeleteAllNotificationsHistory%' then 'kindle_reach_kindle_notifications_delete_all_notification_history'
			when destination_path ilike '%Kindle.Reach.KindleNotifications.InappNotificationEvents%' then 'kindle_reach_kindle_notifications_in_app_notifications_events'
			when destination_path ilike '%Kindle.Reach.KindleNotifications.InAppNotifications%' then 'kindle_reach_kindle_notifications_in_app_notifications'
			when destination_path ilike '%Kindle.Reach.KindleNotifications.RegisteredDeviceEndpoints%' then 'kindle_reach_kindle_notifications_registered_device_endpoints'
			when destination_path ilike '%Kindle.reading-insights-sessions_with_adjustments%' then 'kindle_reading_insights_sessions_adjustments'
			when destination_path ilike '%Kindle.WebReader.lookInsideTheBook%' then 'kindle_web_reader_look_inside_book'
			when destination_path ilike '%library%' then 'library'
			when destination_path ilike '%listening%' then 'listening'
			when destination_path ilike '%Lists%' then 'lists'
			when destination_path ilike '%Mobile_Push_Notification_Permission%' then 'mobile_push_nofication_permission'
			when destination_path ilike '%MobileApp%' then 'mobile_app'
			when destination_path ilike '%MobileInApp%' then 'mobile_in_app'
			when destination_path ilike '%MobileConsumableInApp%' then 'mobileConsumableInApp'
			when destination_path ilike '%MyLikes%' then 'my_likes'
			when destination_path ilike '%Music%Alarms%' then 'music_alarms'
			when destination_path ilike '%NewsPreferences%' then 'news_preferences'
			when destination_path ilike '%node_metadata%' then 'node_metadata'
			when destination_path ilike '%Notification Subscriptions%' then 'notifications_subscription'
			when destination_path ilike '%Notifications History%' then 'notifications_history'
			when destination_path ilike '%Other-Data-Categories.Amazon-Custom%' then 'other_data_categories_custom'
			when destination_path ilike '%OtherBusiness.Rancor%' then 'other_business_rancor'
			when destination_path ilike '%OutboundNotifications.AmazonApplicationUpdateHistory%' then 'outbound_notifications_custom'
			when destination_path ilike '%OutboundNotifications.AmazonShoppingNotificationHubOpen%' then 'outbound_notifications_application_update_history'
			when destination_path ilike '%OutboundNotifications.EmailDeliveryStatusFeedback%' then 'outbound_notification_email_delivery_status_feedback'
			when destination_path ilike '%OutboundNotifications.NotificationEngagementEvents%' then 'outbound_notifications_engagment_events'
			when destination_path ilike '%OutboundNotifications.PushSentData%' then 'outbound_notifications_push_sent_data'
			when destination_path ilike '%OutboundNotifications.PushSentData%' then 'outbound_notifications_push_sent_data'
			when destination_path ilike '%OutboundNotifications.SentNotifications%' then 'outbound_notification_sent_notifications'
			when destination_path ilike '%PaymentOptions.ExternallyManagedPayments%' then 'payment_options_externally_managed_reports'
			when destination_path ilike '%PaymentOptions.PaymentInstruments%' then 'payment_options_payment_instructions'
			when destination_path ilike '%Payments.PaymentProducts%' then 'payments_payment_products'
			when destination_path ilike '%Payments.PaymentProducts%' then 'payments_payment_products'
			when destination_path like '%pdi%' then 'pdi'
			when destination_path like '%PDI%' then 'PDI'
			when destination_path ilike '%Periodicals.PrintMagazineSubscriptions.SubscriptionChangeHistory%' then 'print_magazine_subscripton_change_history'
			when destination_path ilike '%Periodicals.PrintMagazineSubscriptions.Subscriptions%' then 'print_magazine_subscriptions'
			when destination_path ilike '%PhysicalStores.WholeFoods.KeyRegistration%' then 'whole_foods_key_registration'
			when destination_path ilike '%PhysicalStores.WholeFoods.LifecycleEvents%' then 'whole_foods_lifecycle_events'
			when destination_path ilike '%PhysicalStores.WholeFoods.TransactionPromotionRedemptions%' then 'whole_foods_transaction_promotion_redemptions'
			when destination_path ilike '%PickAWinner%CustomerResponses%' then 'pick_winner_customer_responses'
			when destination_path ilike '%Playlist%' then 'playlist'
			when destination_path ilike '%Preferences%' then 'preferences'
			when destination_path ilike '%Prime.Acquisition.primeUp%' then 'prime_acquisition_prime_up'
			when destination_path ilike '%Prime.Acquisition.student%' then 'prime_acquisition_student'
			when destination_path ilike '%ProductCompatibility.DataSet%' then 'product_compatibility_data_sets'
			when destination_path ilike '%profile.csv%' then 'profile'
			when destination_path like '%_registration.csv%' then 'registration'
			when destination_path ilike '%Reminders.csv%' then 'reminders'
			when destination_path ilike '%Retail.AmazonRentals.extension_plans%' then 'retail_rental_extension_plans'
			when destination_path ilike '%Retail.AmazonRentals.rental_charge_transactions%' then 'retail_rental_charge_transactions'
			when destination_path ilike '%Retail.AmazonRentals.rental_communications%' then 'retail_rental_communications'
			when destination_path ilike '%Retail.AmazonRentals.rental_contracts%' then 'retail_rental_contracts'
			when destination_path ilike '%Retail.AmazonRentals.rental_events%' then 'retail_rental_events'
			when destination_path ilike '%Retail.AmazonRentals.rental_items%' then 'retail_rental_items'
			when destination_path ilike '%Retail.AmazonRentals.rental_return_shipment_items%' then 'retail_rental_return_shipment_items'
			when destination_path ilike '%Retail.AmazonRentals.rental_return_shipments%' then 'retail_rental_return_shipments'
			when destination_path ilike '%Retail.AmazonRentals.rental_return_shipments_history%' then 'retail_rental_return_shipments_history'
			when destination_path ilike '%Retail.AmazonWebsitesTraffic%' then 'retail_websites_traffic'
			when destination_path ilike '%Retail.CartItems%' then 'retail_cart_items'
			when destination_path ilike '%Retail.ChatTranscripts.MessageTranscriptsCampfire%' then 'retail_chat_transcripts_message_transcripts_campfire'
			when destination_path ilike '%Retail.CommunityShopping.SocialGamification.Stats%' then 'retail_community_shopping_social_gamification_stats'
			when destination_path ilike '%Retail.CustomerLoginWithAmazonTransactions%' then 'retail_customer_login_with_amazon_transactions'
			when destination_path ilike '%Retail.CustomerProfile.ProfileAttributes%' then 'retail_customer_profile_profile_attributes'
			when destination_path ilike '%Retail.CustomerProfile.ContributionVisibility%' then 'retail_customer_profile_contribution_visibility'
			when destination_path ilike '%Retail.CustomerProfile.Images%' then 'retail_customer_profile_contribution_images'
			when destination_path ilike '%Retail.CustomerQuestionsAndAnswers.AnswersPosted%' then 'retail_customer_questions_and_answers_answers_posted'
			when destination_path ilike '%Retail.CustomerQuestionsAndAnswers.CustomerClicksOnIDontKnowOptionForAnswerSolicitationEmail%' then 'retail_customer_questions_and_answers_solicitation_email_idk'
			when destination_path ilike '%Retail.CustomerQuestionsAndAnswers.QuestionsPosted%' then 'retail_customer_questions_and_answers_questions_posted'
			when destination_path ilike '%Retail.CustomerReturns%' then 'retail_customer_returns'
			when destination_path ilike '%Retail.CustomerReviews.AmazonVerifiedPurchases%' then 'retail_customer_reviews_verified_purchases'
			when destination_path ilike '%Retail.CustomerReviews.ReviewsVersions1%' then 'retail_customer_reviews_reviews_versions'
			when destination_path ilike '%Retail.EbtMedicaid%' then 'retail_ebt_medicaid'
			when destination_path ilike '%Retail.Follow%' then 'retail_follow'
			when destination_path ilike '%Retail.OrderHistory%' then 'retail_order_history'
			when destination_path ilike '%Retail.OrdersReturned%' then 'retail_orders_returned'
			when destination_path ilike '%Retail.OrdersReturned.Payments%' then 'retail_orders_returned_payment'
			when destination_path ilike '%Retail.OutboundNotifications.MobileApplications%' then 'retail_outbound_notifications_mobile_applications'
			when destination_path ilike '%Retail.OutboundNotifications.notificationMetadata%' then 'retail_outbound_notifications_metadata'
			when destination_path ilike '%Retail.ProblemWithOrder%' then 'retail_problems_with_orders'
			when destination_path ilike '%Retail.Promotions%' then 'retail_promotions'
			when destination_path ilike '%Retail.RegionAuthority%' then 'retail_region_authority'
			when destination_path ilike '%Retail.Reorder.DigitalDashButton%' then 'retail_reorder_digital_dash_button'
			when destination_path ilike '%Retail.Reorder.DigitalDashCustomerPreference%' then 'retail_reorder_digital_dash_customer_preferences'
			when destination_path ilike '%Retail.Reorder.DigitalDashSummary%' then 'retail_reorder_digital_dash_summary'
			when destination_path ilike '%Retail.Reorder.PushNotificationsData%' then 'retail_reorder_pushNotificationsData'
			when destination_path ilike '%Retail.Seller-Feedback%' then 'retail_seller_feedback'
			when destination_path ilike '%Retail.ShoppingProfile%' then 'retail_shopping_profile'
			when destination_path ilike '%Retails.AutomotiveNA.Garage%' then 'retail_automotive_garage'
			when destination_path ilike '%_RetailWebsite.AuthenticationTokens%' then 'retail_website_authentication_tokens'
			when destination_path ilike '%report%' then 'report'
			when destination_path ilike '%Responses%' then 'responses'
			when destination_path ilike '%Search-Data.Customer-Engagement%' then 'search_data_customer_engagement'
			when destination_path ilike '%Search-Data.Product-Metrics%' then 'search_data_product_metrics'
			when destination_path ilike '%SearchHistory.Images.ClickData.ClickStream%' then 'search_history_click_stream'
			when destination_path ilike '%SearchHistory.Images%' then 'search_history_images'
			when destination_path ilike '%SeriesRelation%' then 'series_relation'
			when destination_path ilike '%Settings%' then 'settings'
			when destination_path ilike '%Sharable%list%' then 'sharable_list'
			when destination_path ilike '%Skills%' then 'skills'
			when destination_path ilike '%Spotify%User%Details%' then 'spotify_user_details'
			when destination_path ilike '%subscription_info%' then 'subscription_info'
			when destination_path ilike '%subscription-period%' then 'subscription_period'
			when destination_path ilike '%subscription-transaction%' then 'subscription_transaction'
			when destination_path ilike '%Subscriptions.RecurringDeliveries.Events%' then 'subscription_recurring_deliveries_events'
			when destination_path ilike '%Subscriptions.RecurringDeliveries.Orders%' then 'subscription_recurring_deliveries_orders'
			when destination_path ilike '%Subscriptions.RecurringDeliveries.Subscriptions%' then 'subscription_recurring_deliveries_subscriptions'
			when destination_path ilike '%SubscriptionsHistory%' then 'subscription_history'
			when destination_path ilike '%Third%Party%Registration%' then 'third_party_registration'
			when destination_path ilike '%Tablets%Backup%Restore%' then 'tablets_backup_restore'
			when destination_path ilike '%TIMECOP_CONFIG_EVENTS%' then 'timecop_config_events'
			when destination_path ilike '%TIMECOP_TRIGGERS%' then 'timecop_triggers'
			when destination_path ilike '%Timers%' then 'timers'
			when destination_path ilike '%Touch%Events%' then 'touch_events'
			when destination_path ilike '%Transcriptions%' then 'transcriptions'
			when destination_path ilike '%TreasureTruck.DataSet.CustomerPreferences%' then 'treasure_truck_customer_preferences'
			when destination_path ilike '%Updates.csv%' and destination_path not ilike '%camera%' then 'updates'
			when destination_path ilike '%User%Selection%' then 'user_selection'
			when destination_path ilike '%UserSessions%' then 'usersessions'
			when destination_path ilike '%User%Stats%' then 'user_stats'
			when destination_path ilike '%VoiceProfileStatus%' then 'voice_profile_status'
			when destination_path ilike '%watchlist%' then 'Watchlist'
			when destination_path ilike '%WatchlistHistory%' then 'watchlist_history'
			when destination_path ilike '%whispersync%' then 'whisper_sync'
			when destination_path ilike '%WHITELISTING_EVENTS%' then 'whitelisting_events'
			when destination_path ilike '%WholeFoodsMarket.Orders%' then 'whole_foods_market_orders'
			when destination_path ilike '%YourFanshopVisits%' then 'fanshop_visits'
			when destination_path ilike '%YourOrders.AmazonDeals.DealOrders%' then 'amazon_deals_orders'
			when destination_path ilike '%Viewing%history%' then 'viewing_history'
				else 'other'	
			end
		when service = 'NETFLIX' then 
			case when destination_path ilike '%Viewinghistory.Description%' then 'viewing_history_description'
				when destination_path ilike '%Netflix%Viewing%History%' then 'viewing_history'
				when destination_path ilike '%SubscriptionHistory%' then 'subscription_history'
				when destination_path ilike '%ViewingActivity%' then 'viewing_activity'
				when destination_path ilike '%devices%' then 'device'
				when destination_path ilike '%billing_history%' then 'billing_history'
				when destination_path ilike '%ProductCancellationSurvey%' then 'product_cancellation_survey'
				when destination_path ilike '%SearchHistory%' then 'search_history'
				when destination_path ilike '%Ratings%' then 'ratings'
				when destination_path ilike '%PlaybackRelatedEvents%' then 'playback_related_events'
				when destination_path ilike '%MyList%' then 'my_list'
				when destination_path ilike '%Clickstream%' then 'click_stream'
				when destination_path ilike '%BillingHistory%' then 'billing_history'
				when destination_path ilike '%InteractiveTitles%' then 'interactive_titles'
				when destination_path ilike '%IndicatedPreferences%' then 'indicated_preferences'
				when destination_path ilike '%MessagesSentByNetflix%' then 'messages_sent_by_netflix'
				when destination_path ilike '%IpAddresses%' then 'ip_addresses'
				when destination_path ilike '%CSContact%' then 'cs_contact' 
				when destination_path ilike '%watch-history%' then 'watch_history'
				when destination_path ilike '%netflix other%' then 'netflix_other'
				else 'other'
			end
		when service = 'HULU' then 
			case 
				when destination_path ilike '%HULU-DATA%' or destination_path ilike '%Hulu Data%' or destination_path ilike '%hulu%data%' then 'hulu_data'
				when destination_path ilike '%hulu%.pdf%' and destination_path not ilike '%Data%' then 'hulu_pdf_other'
				when destination_path ilike '%HULU%report%' or destination_path ilike '%hulu%report%' or destination_path ilike '%Hulu%Report%' then 'hulu_report'
				when destination_path ilike '%hulu%rtk-report%' then 'hulu_rtk_report'
				when destination_path ilike '%JDunston%' then 'jdunston'
				when destination_path ilike '%MyActivity%' then 'my_activity'
				when destination_path ilike '%StreamingHistory%' then 'streaming_history'
				when destination_path ilike '%ViewingHistory%' then 'viewing_history'
				when destination_path ilike '%watch-history%' then 'watch_history'
				else 'other'
			end
		when service = 'APPLE' then 
			case 
				WHEN destination_path ilike '%Account History - Account Details%' then 'account_history_account_details'
				WHEN destination_path ilike '%Account History - Apple Media Products Welcome Page Action%' then 'account_history_welcome_page'
				WHEN destination_path ilike '%Account History - TV Provider Opt-In History%' then 'account_history_opt_in_history'
				WHEN destination_path ilike '%AMP Purchase History Page & Click Activity%' then 'amp_purchase_history_click_activity'
				WHEN destination_path ilike '%App Authorization History%' then 'app_authorization_history'
				WHEN destination_path ilike '%Apple Books Collection Information%' then 'apple_books_collection_information'
				WHEN destination_path ilike '%Apple Books Global Annotations%' then 'apple_books_global_annotations'
				WHEN destination_path ilike '%Apple Books User Annotations%' then 'apple_books_user_annotations'
				WHEN destination_path ilike '%Apple ID Account Information%' then 'apple_id_account_information'
				WHEN destination_path ilike '%Apple ID Device Information%' then 'apple_id_device_information'
				WHEN destination_path ilike '%Apple ID SignOn Information%' then 'apple_id_signon_information'
				WHEN destination_path ilike '%Apple Music Click Activity%' then 'apple_music_click_activity'
				WHEN destination_path ilike '%Apple Music Library Activity%' then 'apple_music_library_activity'
				WHEN destination_path ilike '%Apple Music Library Playlists%' then 'apple_music_library_playlists'
				WHEN destination_path ilike '%Apple Music Library Tracks%' then 'apple_music_library_tracks'
				WHEN destination_path ilike '%Apple Music Likes and Dislikes%' then 'apple_music_likes_dislikes'
				WHEN destination_path ilike '%Apple Music Listening To Profile Hides%' then 'apple_music_listening_profile_hides'
				WHEN destination_path ilike '%Apple Music Play Activity%' then 'apple_music_play_activity'
				WHEN destination_path ilike '%Apple Music - Recently Played Containers%' then 'apple_music_recently_played_containers'
				WHEN destination_path ilike '%Apple Music - Recently Played Tracks%' then 'apple_music_recently_played_tracks'
				WHEN destination_path ilike '%Apple One Offer Information%' then 'apple_one_offer_information'
				WHEN destination_path ilike '%Apple TV Bookmarks%' then 'apple_tv_bookmarks'
				WHEN destination_path ilike '%Apple TV Favorites and Wishlist%' then 'apple_tv_favorite_wishlist'
				WHEN destination_path ilike '%Apple TV Movie Store Actions%' then 'apple_tv_movie_store_actions'
				WHEN destination_path ilike '%Apps And Service Analytics%' then 'apps_service_analytics'
				WHEN destination_path ilike '%App Store Click Activity%' then 'app_store_click_activity'
				WHEN destination_path ilike '%Billing Information History%' then 'billing_information_history'
				WHEN destination_path ilike '%Bookstore Click Activity%' then 'bookstore_click_activity'
				WHEN destination_path ilike '%CarPlay and Android Auto History%' then 'carplay_android_auto_history'
				WHEN destination_path ilike '%Customer Device History - Computer Authorizations%' then 'customer_device_history_computer_authorization'
				WHEN destination_path ilike '%Customer Device History - iTunes in the Cloud Authorization%' then 'customer_device_history_itunes_cloud_authorization'
				WHEN destination_path ilike '%Customer Device History - Push Notification Authorization%' then 'customer_device_history_push_notification_authorization'
				WHEN destination_path ilike '%Data & Privacy Request History%' then 'data_privacy_request_history'
				WHEN destination_path ilike '%Direct Top-Up Promotions%' then 'direct_top_up_promotions'
				WHEN destination_path ilike '%Fitness Plus Activity%' then 'fitness_plus_activity'	
				WHEN destination_path ilike '%Identifier Information%' then 'identifier_information'
				WHEN destination_path ilike '%iTunes and App-Book Re-download and Update History%' then 'itune_app_book_redownload_update_history'
				WHEN destination_path ilike '%iTunes and App Store Hidden Purchases%' then 'itunes_app_store_hidden_purchases'
				WHEN destination_path ilike '%iTunes Gift Card Redemption Balance History%' then 'itunes_gift_card_redemption_balance_history'
				WHEN destination_path ilike '%iTunes Gift Card Redemption History%' then 'itunes_gift_card_redemption_history'
				WHEN destination_path ilike '%iTunes Match Re-download History%' then 'itunes_match_redownload_history'
				WHEN destination_path ilike '%iTunes Payment Stack - Activity%' then 'itunes_payment_stack_activity'
				WHEN destination_path ilike '%iTunes Wishlist%' then 'itunes_wishlist'
				WHEN destination_path ilike '%Limit Ad Tracking Information%' then 'limit_ad_tracking_information'
				WHEN destination_path ilike '%Linked Services%' then 'linked_services'
				WHEN destination_path ilike '%Media Preview - ebooks%' then 'media_preview_ebooks'
				WHEN destination_path ilike '%Media Preview - previewed%' then 'media_preview_previewed'
				WHEN destination_path ilike '%Media Preview - tagged%' then 'media_preview_tagged'
				WHEN destination_path ilike '%Movies Anywhere Entitlements%' then 'movies_anywhere_entitlements'
				WHEN destination_path ilike '%Music - Favorite Stations%' then 'music_favorite_stations'
				WHEN destination_path ilike '%Music - Liked Radio Tracks%' then 'music_linked_radio_tracks'
				WHEN destination_path ilike '%Music - Onboarding Artists%' then 'music_onboarding_artists'
				WHEN destination_path ilike '%Music - Onboarding Genres%' then 'music_onboarding_genres'	
				WHEN destination_path ilike '%Notification Preferences%' then 'notification_preferences'
				WHEN destination_path ilike '%notifications%' then 'notifications'
				WHEN destination_path ilike '%Playback Activity%' then 'playback_activity'
				WHEN destination_path ilike '%Playlist Moderation%' then 'playlist_moderation'
				WHEN destination_path ilike '%Podcast Preferences%' then 'podcast_preferences'
				WHEN destination_path ilike '%Podcasts Playstate%' then 'podcast_playstate'
				WHEN destination_path ilike '%Pre-order History%' then 'preorder_history'
				WHEN destination_path ilike '%Profile and Sporting Events%' then 'profile_sporting_events'
				WHEN destination_path ilike '%Ratings%' then 'ratings'
				WHEN destination_path ilike '%Redemption Click Activity%' then 'redemption_click_activity'
				WHEN destination_path ilike '%Review profile%' then 'review_profile'
				WHEN destination_path ilike '%Reviews%' then 'reviews'
				WHEN destination_path ilike '%Social and Connect Post Information%' then 'social_connect_post_information'
				WHEN destination_path ilike '%Station - Most Recent%' then 'station_most_recent'
				WHEN destination_path ilike '%Store Free Transaction History%' then 'station_free_transaction_history'
				WHEN destination_path ilike '%Store Transaction History%' then 'store_transaction_history'
				WHEN destination_path ilike '%Streaming Services%' then 'streaming_services%' 
				WHEN destination_path ilike '%Subscription History%' then 'subscription_history'	
				WHEN destination_path ilike '%Testflight Data History-acceptedTerms%' then 'testflight_data_history_accepted_terms'
				WHEN destination_path ilike '%Testflight Data History-betaApp%' then 'testflight_data_history_beta_app'
				WHEN destination_path ilike '%Testflight Data History-crashes%' then 'testflight_data_history_crashes'
				WHEN destination_path ilike '%Testflight Data History-devices%' then 'testflight_data_history_devices'
				WHEN destination_path ilike '%Testflight Data History-feedback%' then 'testflight_data_history_feedback'
				WHEN destination_path ilike '%Testflight Data History-installs%' then 'testflight_data_history_installs'
				WHEN destination_path ilike '%Testflight Data History-sessions%' then 'testflight_data_history_sessions'
				WHEN destination_path ilike '%TV App Favorites and Activity%' then 'tv_app_favorites_activity'
				WHEN destination_path ilike '%TV App with Channel Support Click Activity%' then 'tv_app_channel_support_click_activity'
				WHEN destination_path ilike '%Video Play Activity%' then 'video_play_activity'
				WHEN destination_path ilike '%Votes%' then 'votes'
				WHEN destination_path ilike '%Watchlist%' then 'watchlist'
				WHEN destination_path ilike '%Web Preview Pages%' then 'web_preview_pages'
				WHEN destination_path ilike '%Your Podcasts%' then 'your_podcasts'
				ELSE 'other'
			end
	end as collection
from warehouse_log
{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  where upload_id >= (select max(upload_id) from {{ this }})

{% endif %}